apiVersion: v1
kind: Pod
metadata:
  name: jenkins_agent
  labels:
    app: jenkins_agent
spec:
  containers:
  - image: jenkins/jnlp-slave
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always